name: CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build-windows:
    runs-on: windows-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'

    - name: Setup Rust
      uses: dtolnay/rust-toolchain@stable
      with:
        components: rustfmt, clippy

    - name: Rust cache
      uses: swatinem/rust-cache@v2
      with:
        workspaces: './src-tauri -> target'

    - name: Install frontend dependencies
      run: npm install

    - name: Check Rust formatting
      run: |
        cd src-tauri
        cargo fmt --all -- --check

    - name: Run Rust linting
      run: |
        cd src-tauri
        cargo clippy --all-targets --all-features -- -D warnings

    - name: Run Rust tests
      run: |
        cd src-tauri
        cargo test

    - name: Build Tauri application
      run: npm run build

    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: windows-build
        path: |
          src-tauri/target/release/bundle/
          src-tauri/target/release/*.exe
        retention-days: 30